server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data/ms_order_product.db
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.suresell.order.serivices: INFO
  application:
    name: ms-order-product

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Cupones
coupon:
  admin:
    password: Admin2025*

# CONFIGURACIÓN OFFLINE-FIRST
# Cache persistente en disco
cache:
  enabled: true
  path: ./cache
  ttl-minutes: 60
  cleanup:
    enabled: true
    cron: "0 0 19 * * ?"  # 19:00 todos los días (zona America/Bogota)

sync:
  scheduler:
    fixed-delay-ms: 5000
    batch-size: 20
  cloud:
    enabled: true
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/pos_db
      username: andrewramirez
      password: "sul4m1995*"
