-- =====================================================================
-- F4 Inc.3 (docs/200) — dominio de MESEROS multi-tenant + idempotencia móvil.
--
--  * `waiters` y `waiter_sessions`: espejo de las tablas del ms-order-waiter
--    legacy (waiters / active_sessions) pero con tenant_id + RLS FORCE.
--  * `orders.idempotency_key`: el cliente móvil reintenta con la misma clave y
--    el índice único por-tenant impide órdenes duplicadas (el esquema legacy ya
--    lo tenía; el multi-tenant lo había perdido).
--  * `orders.waiter_id` / `orders.waiter_session_id`: autoría del mesero, para
--    el resumen de turno y para que cocina muestre quién tomó el pedido.
-- =====================================================================

CREATE TABLE waiters (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       TEXT NOT NULL,
    name            TEXT NOT NULL,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    daily_sale_goal NUMERIC(12,2)
);

CREATE TABLE waiter_sessions (
    id                UUID PRIMARY KEY,
    tenant_id         TEXT NOT NULL,
    waiter_id         BIGINT NOT NULL,
    waiter_name       TEXT,
    status            TEXT NOT NULL DEFAULT 'ACTIVE',
    login_time        TIMESTAMP NOT NULL,
    logout_time       TIMESTAMP,
    opening_cash_base NUMERIC(15,2),
    declared_cash     NUMERIC(15,2),
    expected_cash     NUMERIC(15,2),
    difference        NUMERIC(15,2),
    closed_at         TIMESTAMP
);

ALTER TABLE orders ADD COLUMN idempotency_key   TEXT;
ALTER TABLE orders ADD COLUMN waiter_id         BIGINT;
ALTER TABLE orders ADD COLUMN waiter_session_id UUID;

-- Dedupe de reintentos del móvil: única POR TENANT (dos negocios pueden generar
-- la misma clave client-side sin chocar).
CREATE UNIQUE INDEX ux_orders_tenant_idempotency
    ON orders (tenant_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

-- Mismo patrón RLS de V1/V2 para las tablas nuevas.
DO $$
DECLARE
    t TEXT;
    tables TEXT[] := ARRAY['waiters', 'waiter_sessions'];
BEGIN
    FOREACH t IN ARRAY tables LOOP
        EXECUTE format('CREATE INDEX idx_%1$s_tenant ON %1$s (tenant_id)', t);
        EXECUTE format('ALTER TABLE %1$s ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('ALTER TABLE %1$s FORCE ROW LEVEL SECURITY', t);
        EXECUTE format(
            'CREATE POLICY tenant_isolation_%1$s ON %1$s '
            'USING (tenant_id = current_setting(''app.tenant_id'', true)) '
            'WITH CHECK (tenant_id = current_setting(''app.tenant_id'', true))', t);
        EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %1$s TO app_user', t);
    END LOOP;
END
$$;

GRANT USAGE, SELECT ON SEQUENCE waiters_id_seq TO app_user;
