-- =====================================================================
-- F5 cluster caja (PLAN.md A10): gastos de caja registrables EN CUALQUIER
-- momento del turno (no solo al cerrar). El cierre del día los precarga como
-- gastos menores. Mismo patrón RLS de V1/V2.
-- Numeración coordinada entre ramas f5: V11=meseros, V13=pagos, V14=bajas.
-- =====================================================================

CREATE TABLE register_expenses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    TEXT NOT NULL,
    expense_date DATE NOT NULL,
    concept      TEXT NOT NULL,
    amount       NUMERIC(15,2) NOT NULL,
    created_by   TEXT,
    created_at   TIMESTAMP NOT NULL
);

CREATE INDEX idx_register_expenses_tenant ON register_expenses (tenant_id);
CREATE INDEX idx_register_expenses_date ON register_expenses (tenant_id, expense_date);
ALTER TABLE register_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE register_expenses FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_register_expenses ON register_expenses
    USING (tenant_id = current_setting('app.tenant_id', true))
    WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
GRANT SELECT, INSERT, UPDATE, DELETE ON register_expenses TO app_user;
GRANT USAGE, SELECT ON SEQUENCE register_expenses_id_seq TO app_user;
