-- =====================================================================
-- F5 cluster pagos (PLAN.md A11): MULTIPAGO — una orden puede pagarse con
-- varios medios (efectivo + tarjeta + ...). Cada split queda en order_payments;
-- orders.payment_method queda 'MIXED' cuando hay más de un medio.
-- El cierre suma por método: órdenes simples por payment_method + splits.
-- Numeración coordinada ramas f5: V11=meseros, V12=caja, V14=bajas.
-- =====================================================================

CREATE TABLE order_payments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     TEXT NOT NULL,
    order_uuid_id UUID NOT NULL,
    method        TEXT NOT NULL,
    amount        NUMERIC(15,2) NOT NULL,
    created_at    TIMESTAMP NOT NULL
);

CREATE INDEX idx_order_payments_tenant ON order_payments (tenant_id);
CREATE INDEX idx_order_payments_order ON order_payments (tenant_id, order_uuid_id);
ALTER TABLE order_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_payments FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_order_payments ON order_payments
    USING (tenant_id = current_setting('app.tenant_id', true))
    WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
GRANT SELECT, INSERT, UPDATE, DELETE ON order_payments TO app_user;
GRANT USAGE, SELECT ON SEQUENCE order_payments_id_seq TO app_user;
