-- =====================================================================
-- F5 (PLAN.md A15): BAJAS de comida (caída/dañada/vencida) para control.
-- Base para el enganche futuro con inventario (hoy el inventario vive en
-- ms-core-app legacy — ver docs/investigacion/05-proveedores.md).
-- Numeración ramas f5: V11 meseros, V12 caja, V13 pagos, V15 borrado.
-- =====================================================================

CREATE TABLE food_waste (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    TEXT NOT NULL,
    waste_date   DATE NOT NULL,
    product_id   TEXT,
    product_name TEXT NOT NULL,
    quantity     NUMERIC(12,2) NOT NULL,
    reason       TEXT NOT NULL,
    est_cost     NUMERIC(15,2),
    created_by   TEXT,
    created_at   TIMESTAMP NOT NULL
);

CREATE INDEX idx_food_waste_tenant ON food_waste (tenant_id);
CREATE INDEX idx_food_waste_date ON food_waste (tenant_id, waste_date);
ALTER TABLE food_waste ENABLE ROW LEVEL SECURITY;
ALTER TABLE food_waste FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_food_waste ON food_waste
    USING (tenant_id = current_setting('app.tenant_id', true))
    WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
GRANT SELECT, INSERT, DELETE ON food_waste TO app_user;
GRANT USAGE, SELECT ON SEQUENCE food_waste_id_seq TO app_user;
