-- =====================================================================
-- F5 cluster pagos/anti-robo (PLAN.md A13): BORRADO de órdenes por admin.
-- SOFT-DELETE (nunca borrado físico): la orden se marca deleted_at/by y
-- desaparece de historial, cocina, pagers y cierres (filtro global de la
-- entidad), y queda rastro completo en order_deletions (auditoría).
-- Numeración ramas f5: V11 meseros, V12 caja, V13 pagos, V14 bajas.
-- =====================================================================

ALTER TABLE orders ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE orders ADD COLUMN deleted_by TEXT;

CREATE TABLE order_deletions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     TEXT NOT NULL,
    order_uuid_id UUID NOT NULL,
    id_order      BIGINT,
    total         NUMERIC(15,2),
    payment_method TEXT,
    reason        TEXT NOT NULL,
    deleted_by    TEXT NOT NULL,
    created_at    TIMESTAMP NOT NULL
);

CREATE INDEX idx_order_deletions_tenant ON order_deletions (tenant_id);
ALTER TABLE order_deletions ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_deletions FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_order_deletions ON order_deletions
    USING (tenant_id = current_setting('app.tenant_id', true))
    WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
GRANT SELECT, INSERT ON order_deletions TO app_user;
GRANT USAGE, SELECT ON SEQUENCE order_deletions_id_seq TO app_user;
