-- V20 — N2/6.7: rastreadores configurables por negocio.
--
-- Hasta ahora los rastreadores eran fijos: 2 grupos quemados en el enum
-- PagerColor (AMARILLO/AZUL) y 16 unidades por grupo hardcodeadas en el backend
-- (`for i = 1..16`) y en el front (`Array.from({length: 16})`).
--
-- DECISIÓN DE DISEÑO IMPORTANTE — `code` vs `label`:
--   `orders.pager_color` guarda el CÓDIGO del grupo ('AMARILLO', 'AZUL') y hay
--   868 órdenes históricas con esos valores. Por eso el código es INMUTABLE y lo
--   que el negocio edita es `label` (nombre visible) y `color` (hex). Renombrar
--   "AMARILLO" a "Barra" cambia solo lo que ve el cajero; el historial, los
--   cierres y la cocina siguen cuadrando.
--
-- Aditiva y reversible. Rollback en docs/migraciones/V20-rastreadores.md.

CREATE TABLE IF NOT EXISTS tenant_pager_groups (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   text    NOT NULL,
    code        text    NOT NULL,
    label       text    NOT NULL,
    color       text    NOT NULL DEFAULT '#64748b',
    quantity    integer NOT NULL DEFAULT 16,
    sort_order  integer NOT NULL DEFAULT 0,
    CONSTRAINT uq_tenant_pager_groups UNIQUE (tenant_id, code),
    CONSTRAINT ck_tenant_pager_quantity CHECK (quantity >= 0 AND quantity <= 200)
);

CREATE INDEX IF NOT EXISTS idx_tenant_pager_groups_tenant ON tenant_pager_groups (tenant_id);

-- RLS: mismo patrón que el resto de tablas por-tenant.
ALTER TABLE tenant_pager_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_pager_groups FORCE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'tenant_pager_groups' AND policyname = 'tenant_isolation'
    ) THEN
        EXECUTE 'CREATE POLICY tenant_isolation ON tenant_pager_groups
                 USING (tenant_id = current_setting(''app.tenant_id'', true))
                 WITH CHECK (tenant_id = current_setting(''app.tenant_id'', true))';
    END IF;
END $$;

-- Semilla: cada tenant existente arranca EXACTAMENTE como está hoy
-- (2 grupos x 16), para que la configurabilidad no cambie nada por sí sola.
INSERT INTO tenant_pager_groups (tenant_id, code, label, color, quantity, sort_order)
SELECT t.id, 'AMARILLO', 'Amarillo', '#eab308', 16, 0 FROM tenants t
ON CONFLICT (tenant_id, code) DO NOTHING;

INSERT INTO tenant_pager_groups (tenant_id, code, label, color, quantity, sort_order)
SELECT t.id, 'AZUL', 'Azul', '#3b82f6', 16, 1 FROM tenants t
ON CONFLICT (tenant_id, code) DO NOTHING;
