-- V23 — Modo de POS por SEDE (Inc. 1 del modo Restaurante).
--
-- POR QUÉ POR SEDE Y NO POR TENANT: un cliente no puede tener los dos modos en
-- el mismo negocio, pero una CADENA sí puede tener una sede en plazoleta y otra
-- en restaurante (decisión del usuario, 2026-07-26). Colgar el modo del tenant
-- obligaría a moverlo después.
--
-- ALCANCE DELIBERADO: esto NO construye el sistema multisede. Crea la sede como
-- unidad mínima —una "Principal" por negocio— para que el modo y el consecutivo
-- tengan de dónde colgar sin rehacer nada más adelante.
--
-- Aditiva y reversible. Rollback en docs/migraciones/V23-V25-modo-restaurante.md.
--
-- OJO NUMERACIÓN: V21 y V22 ya están aplicadas en prod y V19 quedó sin usar a
-- propósito. Por eso este archivo es V23 y no V21.

CREATE TABLE IF NOT EXISTS sites (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  text    NOT NULL,
    name       text    NOT NULL,
    -- Código corto para la numeración futura (SHARK-BURGER/SED-CHICO-123).
    code       text    NOT NULL,
    pos_mode   text    NOT NULL DEFAULT 'PLAZOLETA',
    active     boolean NOT NULL DEFAULT true,
    is_default boolean NOT NULL DEFAULT false,
    CONSTRAINT uq_sites_tenant_code UNIQUE (tenant_id, code),
    CONSTRAINT ck_sites_pos_mode CHECK (pos_mode IN ('PLAZOLETA', 'RESTAURANTE'))
);

CREATE INDEX IF NOT EXISTS idx_sites_tenant ON sites (tenant_id);

-- Una sola sede por defecto por negocio: el fallback tiene que ser inequívoco.
CREATE UNIQUE INDEX IF NOT EXISTS ux_sites_default
    ON sites (tenant_id) WHERE is_default;

ALTER TABLE sites ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites FORCE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='sites' AND policyname='tenant_isolation') THEN
        EXECUTE 'CREATE POLICY tenant_isolation ON sites
                 USING (tenant_id = current_setting(''app.tenant_id'', true))
                 WITH CHECK (tenant_id = current_setting(''app.tenant_id'', true))';
    END IF;
END $$;

-- LECCIÓN DE V20: una tabla nueva SIN grants deja a la app con "permission
-- denied" aunque la migración pase verde (Flyway corre como owner). RLS no
-- sustituye a los permisos.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE sites TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user;

-- Cada negocio existente arranca con su sede Principal en PLAZOLETA: nadie
-- cambia de comportamiento por esta migración.
INSERT INTO sites (tenant_id, name, code, pos_mode, is_default)
SELECT t.id, 'Principal', 'PRINCIPAL', 'PLAZOLETA', true
FROM tenants t
ON CONFLICT (tenant_id, code) DO NOTHING;

-- Las órdenes y los cierres se anclan a la sede. NULLABLE a propósito: lo
-- existente no se reescribe y el código trata NULL como "sede por defecto".
ALTER TABLE orders         ADD COLUMN IF NOT EXISTS site_id bigint REFERENCES sites(id);
ALTER TABLE daily_closures ADD COLUMN IF NOT EXISTS site_id bigint REFERENCES sites(id);

-- Consecutivo POR SEDE, preservando la secuencia actual de cada negocio.
-- Se agrega la columna en vez de recrear la tabla para NO perder los contadores
-- vivos: romper la continuidad de la numeración es un problema fiscal.
ALTER TABLE tenant_order_counters ADD COLUMN IF NOT EXISTS site_id bigint REFERENCES sites(id);

UPDATE tenant_order_counters c
SET    site_id = s.id
FROM   sites s
WHERE  s.tenant_id = c.tenant_id AND s.is_default AND c.site_id IS NULL;
