-- V24 — Mesas del modo Restaurante (Inc. 2).
--
-- Molde: tenant_pager_groups (V20). Mismo patrón de RLS + política + GRANTs,
-- porque ya está probado y porque olvidar los GRANTs fue el error que tumbó el
-- POS entero cuando se creó V20 sin ellos.
--
-- Las mesas cuelgan de la SEDE: el modo de POS es por sede, así que una cadena
-- puede tener mesas solo en las sedes que operan como restaurante.
--
-- Aditiva y reversible. Rollback en docs/migraciones/V23-V25-modo-restaurante.md.

CREATE TABLE IF NOT EXISTS restaurant_tables (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  text    NOT NULL,
    site_id    bigint  REFERENCES sites(id),
    number     integer NOT NULL,
    label      text,
    seats      integer,
    active     boolean NOT NULL DEFAULT true,
    CONSTRAINT uq_restaurant_tables UNIQUE (tenant_id, site_id, number),
    CONSTRAINT ck_restaurant_tables_number CHECK (number > 0 AND number <= 500)
);

CREATE INDEX IF NOT EXISTS idx_restaurant_tables_tenant ON restaurant_tables (tenant_id);

ALTER TABLE restaurant_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE restaurant_tables FORCE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='restaurant_tables' AND policyname='tenant_isolation') THEN
        EXECUTE 'CREATE POLICY tenant_isolation ON restaurant_tables
                 USING (tenant_id = current_setting(''app.tenant_id'', true))
                 WITH CHECK (tenant_id = current_setting(''app.tenant_id'', true))';
    END IF;
END $$;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE restaurant_tables TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user;
