-- =====================================================================
-- V28 -- Dos cosas que van juntas porque ambas regularizan Produccion:
--
--   A) Las 17 tablas del modulo de administracion, creadas a mano el 27-jul
--      FUERA de Flyway. Sin esto el historial de migraciones miente y un
--      ambiente nuevo levantado desde cero no las tendria. Todo con
--      IF NOT EXISTS: en Prod y Staging ya existen y no hace nada.
--
--   B) Numeracion de ordenes POR SEDE con control fiscal.
--
-- Sobre (B) -- el consecutivo es un dato fiscal. Reglas que esta migracion hace
-- cumplir EN LA BASE, no en el codigo:
--   1. NO se renumera nada emitido. Romper la continuidad de un consecutivo ya
--      emitido es un problema con la DIAN, no un detalle tecnico.
--   2. Cada sede arranca donde iba su negocio, no en 1.
--   3. El consecutivo es unico por (negocio, sede) y NO se reutiliza jamas, ni
--      aunque la orden se borre: el contador solo avanza.
--   4. Todo cambio manual del contador queda registrado con quien y cuando.
-- =====================================================================

-- =====================================================================
-- A) Tablas del modulo de administracion (ms-core-app)
--
-- El DDL es el que YA corre en Prod y Staging: replica del legacy tal cual
-- (tipos, longitudes, defaults e IDENTITY), porque ms-core-app usa
-- ddl-auto: none y cualquier diferencia aparece en tiempo de ejecucion, no al
-- desplegar. `tenant_id` con default: ese servicio no conoce tenants y sus
-- INSERT no lo mandan.
-- =====================================================================

CREATE TABLE IF NOT EXISTS supply_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id TEXT NOT NULL DEFAULT 'shark-burger', name VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS supplies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id TEXT NOT NULL DEFAULT 'shark-burger', created_at TIMESTAMP NOT NULL,
    min_stock NUMERIC(12,2) NOT NULL, name VARCHAR(200) NOT NULL, price NUMERIC(12,2) NOT NULL,
    stock NUMERIC(12,2) NOT NULL, updated_at TIMESTAMP NOT NULL,
    supply_category_id BIGINT NOT NULL REFERENCES supply_categories (id), unit VARCHAR(40));

CREATE TABLE IF NOT EXISTS supply_consumptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id TEXT NOT NULL DEFAULT 'shark-burger', quantity NUMERIC(38,2) NOT NULL,
    reason VARCHAR(255) NOT NULL, registration_date TIMESTAMP NOT NULL,
    supply_id BIGINT NOT NULL REFERENCES supplies (id));

CREATE TABLE IF NOT EXISTS weekly_inventory_counts (
    id BIGSERIAL PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'shark-burger',
    supply_id BIGINT NOT NULL, supply_name VARCHAR(200), counted_quantity NUMERIC(12,2) NOT NULL,
    week_start DATE NOT NULL, source VARCHAR(50), created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL, previous_stock NUMERIC(12,2), difference NUMERIC(12,2));

CREATE TABLE IF NOT EXISTS suppliers (
    id BIGSERIAL PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'shark-burger',
    name VARCHAR(200) NOT NULL, phone VARCHAR(40), active BOOLEAN DEFAULT true);

CREATE TABLE IF NOT EXISTS supplier_requests (
    id BIGSERIAL PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'shark-burger',
    status VARCHAR(20) NOT NULL, source VARCHAR(20), supplier_id BIGINT REFERENCES suppliers (id),
    created_by VARCHAR(255), notes TEXT, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP);

CREATE TABLE IF NOT EXISTS supplier_request_items (
    id BIGSERIAL PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'shark-burger',
    request_id BIGINT NOT NULL REFERENCES supplier_requests (id), supply_id BIGINT,
    product_name VARCHAR(200) NOT NULL, unit VARCHAR(40), quantity NUMERIC(12,2) NOT NULL);

CREATE TABLE IF NOT EXISTS shopping_items (
    id VARCHAR(255) PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'shark-burger',
    created_at TIMESTAMP, current_stock NUMERIC(10,2), estimated_cost NUMERIC(10,2),
    minimum_stock NUMERIC(10,2), name VARCHAR(255) NOT NULL, status VARCHAR(255),
    suggested_quantity NUMERIC(10,2), supply_category VARCHAR(255), unit VARCHAR(255),
    updated_at TIMESTAMP);

CREATE TABLE IF NOT EXISTS employees (
    id BIGSERIAL PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'shark-burger',
    name VARCHAR(255) NOT NULL, document_id VARCHAR(100), phone VARCHAR(50),
    role VARCHAR(255) NOT NULL, payment_mode VARCHAR(50) NOT NULL DEFAULT 'PER_SHIFT',
    base_salary NUMERIC(12,2) NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT now(), updated_at TIMESTAMP);

CREATE TABLE IF NOT EXISTS payrolls (
    id VARCHAR(36) PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'shark-burger',
    code VARCHAR(255) NOT NULL, employee_name VARCHAR(255) NOT NULL, document_id VARCHAR(255),
    phone VARCHAR(255), role VARCHAR(255) NOT NULL,
    payment_mode VARCHAR(50) NOT NULL DEFAULT 'PER_SHIFT', value_per_day NUMERIC(12,2),
    worked_days DOUBLE PRECISION, commissions NUMERIC(12,2), bonuses NUMERIC(12,2),
    total_value NUMERIC(12,2) NOT NULL, notes TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING', payment_date DATE,
    created_by VARCHAR(255) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now(), overtime_value NUMERIC(12,2), employee_id BIGINT);

CREATE TABLE IF NOT EXISTS expense_categories (
    id BIGSERIAL PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'shark-burger',
    name VARCHAR(255) NOT NULL, description VARCHAR(500), active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS expenses (
    id VARCHAR(36) PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'shark-burger',
    code VARCHAR(50) NOT NULL, amount NUMERIC(12,2) NOT NULL, quantity DOUBLE PRECISION,
    unit_price NUMERIC(12,2), description VARCHAR(500) NOT NULL, vendor VARCHAR(255),
    image_url VARCHAR(1000), category_id BIGINT NOT NULL REFERENCES expense_categories (id),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING', expense_date DATE NOT NULL,
    created_by VARCHAR(255) NOT NULL, approved_by VARCHAR(255), approved_at TIMESTAMP,
    rejection_reason VARCHAR(500), notes VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS valeras (
    id VARCHAR(36) PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'shark-burger',
    code VARCHAR(50) NOT NULL, created_at TIMESTAMP NOT NULL,
    customer_document VARCHAR(20) NOT NULL, customer_name VARCHAR(100) NOT NULL,
    customer_phone VARCHAR(20), discount NUMERIC(10,2), expiration_date DATE NOT NULL,
    final_price NUMERIC(10,2) NOT NULL, notes VARCHAR(500), purchase_date DATE NOT NULL,
    remaining_meals INTEGER NOT NULL, status VARCHAR(255) NOT NULL, total_meals INTEGER NOT NULL,
    total_value NUMERIC(10,2) NOT NULL, type VARCHAR(255) NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL, updated_at TIMESTAMP NOT NULL);

CREATE TABLE IF NOT EXISTS meal_preparations (
    id VARCHAR(36) PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'shark-burger',
    beverage VARCHAR(100), created_at TIMESTAMP NOT NULL, day_of_week VARCHAR(255) NOT NULL,
    dessert VARCHAR(200), main_dish VARCHAR(200) NOT NULL, preparation_date DATE NOT NULL,
    side_dish VARCHAR(200), soup VARCHAR(200), special_notes VARCHAR(500),
    updated_at TIMESTAMP NOT NULL);

CREATE TABLE IF NOT EXISTS accounts_receivable (
    id VARCHAR(36) PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'shark-burger',
    created_at TIMESTAMP NOT NULL, credit_limit NUMERIC(12,2) NOT NULL,
    customer_document VARCHAR(20) NOT NULL, customer_name VARCHAR(100) NOT NULL,
    customer_phone VARCHAR(20), last_transaction_date DATE, notes VARCHAR(500),
    status VARCHAR(255) NOT NULL, total_debt NUMERIC(12,2) NOT NULL, updated_at TIMESTAMP NOT NULL);

CREATE TABLE IF NOT EXISTS debt_transactions (
    id VARCHAR(36) PRIMARY KEY, tenant_id TEXT NOT NULL DEFAULT 'shark-burger',
    account_id VARCHAR(36) NOT NULL REFERENCES accounts_receivable (id),
    amount NUMERIC(10,2) NOT NULL, created_at TIMESTAMP NOT NULL, description VARCHAR(500),
    payment_method VARCHAR(255), reference VARCHAR(100), transaction_date DATE NOT NULL,
    type VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS qr_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id TEXT NOT NULL DEFAULT 'shark-burger', payment_date DATE NOT NULL,
    amount NUMERIC(12,2) NOT NULL, notes VARCHAR(255), registered_by VARCHAR(255),
    created_at TIMESTAMP, updated_at TIMESTAMP);

-- LECCION V20/V22: la migracion corre como owner y pasa verde aunque falten los
-- GRANT; la aplicacion conecta con otro rol y recibe "permission denied".
-- RLS no sustituye a los permisos.
DO $grants$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['supply_categories','supplies','supply_consumptions',
      'weekly_inventory_counts','suppliers','supplier_requests','supplier_request_items',
      'shopping_items','employees','payrolls','expense_categories','expenses','valeras',
      'meal_preparations','accounts_receivable','debt_transactions','qr_payments']
  LOOP
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE %I TO app_user', t);
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS app_rw_%I ON %I', t, t);
    EXECUTE format('CREATE POLICY app_rw_%I ON %I FOR ALL TO app_user '
                   || 'USING (true) WITH CHECK (true)', t, t);
  END LOOP;
END $grants$;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user;

-- =====================================================================
-- B) Numeracion por sede con control fiscal
-- =====================================================================

-- B.1 -- El contador pasa a ser por (negocio, SEDE).
-- V23 ya agrego `site_id` a la tabla, pero la PK seguia siendo solo `tenant_id`:
-- en la practica habia UN contador por negocio. La fila existente ya trae su
-- site_id (V23 la anclo a la sede por defecto), asi que cambiar la PK NO pierde
-- ni reinicia ningun contador vivo.
UPDATE tenant_order_counters c
SET    site_id = s.id
FROM   sites s
WHERE  s.tenant_id = c.tenant_id AND s.is_default AND c.site_id IS NULL;

DELETE FROM tenant_order_counters WHERE site_id IS NULL;

ALTER TABLE tenant_order_counters ALTER COLUMN site_id SET NOT NULL;
ALTER TABLE tenant_order_counters DROP CONSTRAINT IF EXISTS tenant_order_counters_pkey;
ALTER TABLE tenant_order_counters ADD CONSTRAINT tenant_order_counters_pkey
    PRIMARY KEY (tenant_id, site_id);

-- B.2 -- Prefijo fiscal visible por sede. El folio impreso pasa a ser
-- `<prefijo>-<consecutivo>`; el prefijo distingue sedes SIN tocar el
-- consecutivo, que es el dato fiscal. Vacio por defecto: una sede unica sigue
-- mostrando el numero pelado, como hoy.
ALTER TABLE sites ADD COLUMN IF NOT EXISTS invoice_prefix VARCHAR(10) NOT NULL DEFAULT '';

COMMENT ON COLUMN sites.invoice_prefix IS
    'Prefijo fiscal del folio de esta sede. Vacio = folio sin prefijo.';

-- B.3 -- Bitacora de cambios manuales del consecutivo. Mover un consecutivo a
-- mano es delicado (se hizo el 26-jul para preservar continuidad tras el
-- cutover): debe quedar quien, cuando, de cuanto a cuanto y por que.
CREATE TABLE IF NOT EXISTS order_counter_audit (
    id            BIGSERIAL   PRIMARY KEY,
    tenant_id     TEXT        NOT NULL,
    site_id       BIGINT      NOT NULL,
    valor_antes   BIGINT      NOT NULL,
    valor_despues BIGINT      NOT NULL,
    motivo        TEXT        NOT NULL,
    hecho_por     TEXT        NOT NULL,
    hecho_en      TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT ON order_counter_audit TO app_user;
GRANT USAGE, SELECT ON SEQUENCE order_counter_audit_id_seq TO app_user;
ALTER TABLE order_counter_audit ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS app_rw_order_counter_audit ON order_counter_audit;
CREATE POLICY app_rw_order_counter_audit ON order_counter_audit
    FOR ALL TO app_user USING (true) WITH CHECK (true);

-- B.4 -- El trigger asigna el consecutivo de la SEDE de la orden.
--   . El contador SOLO AVANZA: nunca se reutiliza un numero, ni aunque la orden
--     se borre despues (el borrado es logico, deleted_at).
--   . Sin sede en la orden se usa la sede por defecto, asi una instalacion de
--     una sola sede se comporta exactamente como antes.
--   . El UPSERT bloquea la fila durante el UPDATE: sin colisiones bajo
--     concurrencia, que es lo que produciria numeros repetidos.
CREATE OR REPLACE FUNCTION set_order_id_order() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER AS $fn$
DECLARE
    next_id      BIGINT;
    sede_destino BIGINT;
BEGIN
    IF NEW.id_order IS NULL THEN
        sede_destino := NEW.site_id;

        IF sede_destino IS NULL THEN
            SELECT id INTO sede_destino
            FROM sites
            WHERE tenant_id = NEW.tenant_id AND is_default
            LIMIT 1;
        END IF;

        -- Un negocio sin sede registrada -recien dado de alta- obtiene la suya
        -- automaticamente. La primera version de esta migracion lanzaba una
        -- excepcion aqui y los tests de integracion demostraron que eso DEJA SIN
        -- VENDER a cualquier negocio nuevo: el alta no crea sedes. Crear la sede
        -- por defecto es lo correcto -todo negocio tiene al menos una- y ademas
        -- garantiza que el consecutivo siempre pertenece a una sede concreta.
        IF sede_destino IS NULL THEN
            INSERT INTO sites (tenant_id, name, code, is_default)
            VALUES (NEW.tenant_id, 'Principal', 'PRINCIPAL', true)
            ON CONFLICT (tenant_id, code) DO NOTHING;

            SELECT id INTO sede_destino
            FROM sites
            WHERE tenant_id = NEW.tenant_id AND is_default
            LIMIT 1;
        END IF;

        INSERT INTO tenant_order_counters (tenant_id, site_id, last_id)
        VALUES (NEW.tenant_id, sede_destino, 1)
        ON CONFLICT (tenant_id, site_id)
        DO UPDATE SET last_id = tenant_order_counters.last_id + 1
        RETURNING last_id INTO next_id;

        NEW.id_order := next_id;
        NEW.site_id  := sede_destino;
    END IF;
    RETURN NEW;
END $fn$;

-- B.5 -- Unicidad del consecutivo POR SEDE. Dos sedes del mismo negocio pueden
-- llevar el mismo numero; lo que no puede repetirse es dentro de una sede.
ALTER TABLE orders DROP CONSTRAINT IF EXISTS uq_orders_tenant_id_order;

CREATE UNIQUE INDEX IF NOT EXISTS uq_orders_sede_consecutivo
    ON orders (tenant_id, site_id, id_order)
    WHERE deleted_at IS NULL;

-- B.6 -- Continuidad: cada sede arranca donde iba su negocio. Sin esto una sede
-- nueva empezaria en 1 y pisaria numeros ya emitidos.
INSERT INTO tenant_order_counters (tenant_id, site_id, last_id)
SELECT s.tenant_id, s.id,
       COALESCE((SELECT MAX(o.id_order) FROM orders o
                  WHERE o.tenant_id = s.tenant_id
                    AND (o.site_id = s.id OR o.site_id IS NULL)), 0)
FROM sites s
ON CONFLICT (tenant_id, site_id) DO UPDATE
   SET last_id = GREATEST(tenant_order_counters.last_id, EXCLUDED.last_id);

-- B.7 -- Bitacora del cambio de modo (Plazoleta <-> Restaurante).
-- Es una accion de alto impacto operativo: debe quedar quien y cuando.
CREATE TABLE IF NOT EXISTS site_mode_audit (
    id           BIGSERIAL   PRIMARY KEY,
    tenant_id    TEXT        NOT NULL,
    site_id      BIGINT      NOT NULL,
    modo_antes   TEXT        NOT NULL,
    modo_despues TEXT        NOT NULL,
    hecho_por    TEXT        NOT NULL,
    hecho_en     TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT ON site_mode_audit TO app_user;
GRANT USAGE, SELECT ON SEQUENCE site_mode_audit_id_seq TO app_user;
ALTER TABLE site_mode_audit ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS app_rw_site_mode_audit ON site_mode_audit;
CREATE POLICY app_rw_site_mode_audit ON site_mode_audit
    FOR ALL TO app_user USING (true) WITH CHECK (true);
