-- =====================================================================
-- V29 — DIVISIÓN DE CUENTA entre N comensales (último pendiente del bloque 3
-- de docs/v2-final/05-FEATURES-FALTANTES-V2.md).
--
-- Repartir el total de una mesa entre N no da pesos enteros. La decisión de
-- negocio tomada es: **el negocio absorbe el redondeo, nunca el comensal**.
-- Nunca se cobra de más; los pesos sobrantes no se le cobran a nadie.
--
-- Ese residuo NO puede desaparecer en silencio: el catálogo comercial promete
-- cierres "auditables al peso".
--
-- DECISIÓN DEL 2026-08-04 (revisada tras la primera prueba): el ajuste **NO se
-- guarda desnormalizado** ni en `table_sessions` ni en `daily_closures`. En vez
-- de eso, cada división deja su propio registro de auditoría acá, y el cierre
-- de caja **suma al vuelo** lo que corresponde a su ventana.
--
-- Por qué así:
--   · Una sola fuente de verdad. Un campo copiado en dos tablas es un campo que
--     algún día va a discrepar, y en dinero eso es un incidente.
--   · La pregunta que de verdad hace un auditor no es "cuánto se absorbió" sino
--     "POR QUÉ": qué mesa, cuántos comensales, quién cobró y con qué pagó cada
--     uno. Un número suelto en el cierre no responde nada de eso; esta tabla sí.
--
-- ADITIVA Y REVERSIBLE. Solo crea una tabla nueva: no toca ninguna columna ni
-- ninguna fila existente, así que las 4.033 órdenes y los cierres ya guardados
-- no se enteran.
--
-- Rollback (se pierde el detalle de auditoría de las divisiones ya cobradas):
--   DROP TABLE IF EXISTS table_session_splits;
-- =====================================================================

CREATE TABLE IF NOT EXISTS table_session_splits (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           TEXT          NOT NULL,
    table_session_id    UUID          NOT NULL REFERENCES table_sessions(id),

    -- El reparto, tal como se calculó.
    personas            INTEGER       NOT NULL,
    total               NUMERIC(15,2) NOT NULL,  -- el total de la mesa, intacto
    por_persona         NUMERIC(15,2) NOT NULL,  -- floor(total / personas)
    cobrado             NUMERIC(15,2) NOT NULL,  -- por_persona * personas
    ajuste_redondeo     NUMERIC(15,2) NOT NULL,  -- total - cobrado, lo que asume el negocio

    -- Con qué pagó cada comensal, en JSON:
    --   [{"persona":1,"metodo":"CASH","monto":3333}, ...]
    -- Se guarda como TEXT igual que `daily_closures.cash_count_audit`, que es la
    -- convención que ya usa el proyecto para auditorías.
    detalle_por_persona TEXT          NOT NULL,

    created_at          TIMESTAMP     NOT NULL,
    created_by          TEXT,

    -- El invariante, sostenido por la BASE y no solo por el código: si alguna
    -- vez se inserta un reparto que no cuadra, la fila se rechaza.
    CONSTRAINT ck_split_cuadra   CHECK (cobrado + ajuste_redondeo = total),
    CONSTRAINT ck_split_personas CHECK (personas >= 2),
    -- Nunca hacia arriba: lo cobrado jamás puede superar el total de la mesa.
    CONSTRAINT ck_split_no_cobra_de_mas CHECK (cobrado <= total AND ajuste_redondeo >= 0)
);

-- El cierre de caja suma por ventana de tiempo: ese es el índice que importa.
CREATE INDEX IF NOT EXISTS idx_table_session_splits_tenant_fecha
    ON table_session_splits (tenant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_table_session_splits_sesion
    ON table_session_splits (table_session_id);

ALTER TABLE table_session_splits ENABLE ROW LEVEL SECURITY;
ALTER TABLE table_session_splits FORCE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies
                   WHERE tablename='table_session_splits' AND policyname='tenant_isolation') THEN
        EXECUTE 'CREATE POLICY tenant_isolation ON table_session_splits
                 USING (tenant_id = current_setting(''app.tenant_id'', true))
                 WITH CHECK (tenant_id = current_setting(''app.tenant_id'', true))';
    END IF;
END $$;

-- Regla dura del proyecto: toda tabla nueva deja explícito el permiso del rol de
-- aplicación. Sin esto, RLS + un GRANT faltante = "error siempre" en la feature.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE table_session_splits TO app_user;
GRANT USAGE, SELECT ON SEQUENCE table_session_splits_id_seq TO app_user;
