-- =====================================================================
-- Tabla de infraestructura `sync_outbox` para el perfil cloud.
--
-- OrderHandler SIEMPRE encola un evento en sync_outbox al crear/editar una orden
-- (patrón outbox del local-first). En el perfil cloud el scheduler que lo drena
-- está apagado (sync.cloud.enabled=false), pero el INSERT igual ocurre dentro de
-- la transacción de la orden: si la tabla no existe, la orden hace rollback.
--
-- NO es una tabla de tenant (no lleva tenant_id ni RLS): es infra interna. Como
-- en cloud nunca se drena, sus filas quedan inertes. (Mejora futura: que el
-- handler omita el encolado cuando el outbox está deshabilitado.)
-- =====================================================================

CREATE TABLE sync_outbox (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type TEXT NOT NULL,
    aggregate_id   BIGINT NOT NULL,
    aggregate_uuid UUID,
    event_type     TEXT NOT NULL,
    payload_json   TEXT NOT NULL,
    status         TEXT NOT NULL,
    attempts       INT NOT NULL,
    next_retry_at  BIGINT NOT NULL,
    last_error     TEXT,
    created_at     BIGINT NOT NULL,
    updated_at     BIGINT NOT NULL,
    synced_at      BIGINT
);

GRANT SELECT, INSERT, UPDATE, DELETE ON sync_outbox TO app_user;
